deadline/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, move, unmove, erase, add_deadline_service

app_name= 'deadline'

urlpatterns = [
    path('', index, name='index'),
    path('<int:pk>', move, name='done'),
    path('del/<int:pk>', unmove, name='undone'),
    path('delete/<int:pk>', erase, name='erase'),
    path('add_dl_service/', add_deadline_service, name='add_dl_service')
]

jadwal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import CalendarView, event

app_name = "jadwal"

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/$', event, name='event_new'),
    path('event/edit/<int:event_id>', event, name='event_edit'),
]

nara_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('deadline/', include('deadline.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('profil/', include('profil.urls')),
    path('nilai/', include('nilai.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nilai/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.masuk_data, name='idx'),
	path('hitung/', views.hitung_ip, name='hitung'),
	path('hapus/', views.reset, name='hapus'),
	path('getData/', views.getJSON, name='ambil'),
]

deadline/models.py
from django.db import models

# Create your models here.
class dl(models.Model):
    nama_deadline = models.CharField(max_length=25,blank=True, verbose_name='')
    selesai = models.BooleanField(default=False)

    def __str__(self):
        return self.nama_deadline 

deadline/forms.py
from django import forms
from .models import dl

class deadlines(forms.Form):
    # class Meta:
    #     model = dl
    #     fields = ['nama_deadline']
    #     widgets = {
    #         'nama_deadline' : forms.TextInput(attrs={'placeholder':'Type your schedule here', 'style': 'border:0; width:100%'})
    #     }
    daftar_deadline = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Type your schedule here',
        'type' : 'text',
        'maxlength' : '25',
        'required' : True,
    }))

deadline/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.contrib import messages
from .forms import deadlines
from .models import dl

# from reminder.forms import TodoForm
# from reminder.models import Todo
# Create your views here.

def index(request):
    if request.method == 'POST':
        form = deadlines(request.POST)
        if form.is_valid():
            list_dl = dl()
            list_dl.nama_deadline = form.cleaned_data["daftar_deadline"]
            list_dl.save()
        return redirect('/deadline')
    else:
        form = deadlines()

        # reminder_form = TodoForm()
        # listTodo = Todo.objects.all()
        # listSize = listTodo.count()

        list_dl= dl.objects.all()
        sudah = 0
        belum = 0
        for i in list_dl:
            if(i.selesai):
                sudah += 1
            else:
                belum += 1
        context = {'form':form, 'list_dl':list_dl, 'sudah':sudah, 'belum':belum} #'rForm':reminder_form, 'listTodo':listTodo, 'listSize':listSize}
        return render(request, 'deadline/index.html', context)

def move(request, pk):
    tmp = dl.objects.get(pk=pk)
    tmp.selesai = True
    tmp.save()

    return redirect('/deadline')

def unmove(request, pk):
    tmp = dl.objects.get(pk=pk)
    tmp.selesai = False
    tmp.save()

    return redirect('/deadline')

def erase(request, pk):
    if request.method == 'POST':
        form = deadlines(request.POST)
        if form.is_valid():
            list_dl = dl()
            list_dl.nama_deadline = form.cleaned_data["daftar_deadline"]
            list_dl.save()
        return redirect('/deadline')
    else:
        dl.objects.filter(pk=pk).delete()
        form = deadlines()

        # reminder_form = TodoForm()
        # listTodo = Todo.objects.all()
        # listSize = listTodo.count()

        list_dl= dl.objects.all()
        sudah = 0
        belum = 0
        for i in list_dl:
            if(i.selesai):
                sudah += 1
            else:
                belum += 1
        context = {'form':form, 'list_dl':list_dl, 'sudah':sudah, 'belum':belum} #'rForm':reminder_form, 'listTodo':listTodo, 'listSize':listSize}
        return render(request, 'deadline/index.html', context)

def add_deadline_service(request):
    if request.method == 'POST':
        form = deadlines(request.POST)
        print(form.errors)
        print(form.is_valid())
        print(request.POST)
        if form.is_valid():
            list_dl = dl()
            list_dl.nama_deadline = form.cleaned_data["daftar_deadline"]
            list_dl.save()
            result = dl.objects.all()
            data = serializers.serialize('json', result, fields = ('nama_deadline', 'selesai'))
            return JsonResponse({'results':data})
        return JsonResponse({'message' : "error when saving the data"})

    else:
        form = deadlines()

        list_dl= dl.objects.all()
        sudah = 0
        belum = 0
        for i in list_dl:
            if(i.selesai):
                sudah += 1
            else:
                belum += 1
        context = {'form':form, 'list_dl':list_dl, 'sudah':sudah, 'belum':belum} #'rForm':reminder_form, 'listTodo':listTodo, 'listSize':listSize}
        return render(request, 'deadline/index.html', context)

deadline/templates/deadline/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'deadline/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="font-family: 'Montserrat';">
    <nav class="navbar navbar-expand-lg navbar-light navbar-navbarcolor py-3" style="background-color: #F6E0BB;">
        <a class="navbar-brand" href="{% url 'landing' %}">
            <img src="{% static 'images/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <b><i>Project Nara</i></b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-md-2">
                <a class="nav-link" href="{% url 'jadwal:calendar' %}">Jadwal<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-md-2">
                <a class="nav-link" href="{% url 'deadline:index' %}">Deadline</a>
            </li>
            <li class="nav-item mr-md-2">
                <a class="nav-link" href="{% url 'idx' %}">Kalkulator IPK</a>
            </li>
            <li class="nav-item mr-md-2">
                    <a class="nav-link" href="{% url 'profil' %}">Profil</a>
                </li>
            <li class="nav-item mr-md-2">
                <a class="nav-link" href="{% url 'tentang' %}">Tentang Kami</a>
            </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block script %}
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% endblock %}
</body>
</html>

deadline/templates/deadline/index.html
{% extends 'deadline/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'deadline/css/style.css' %}">
{% endblock %}

    {% block content %}
    <body style="width: 100%;">
        <section>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 mt-5 mb-3 ml-3">
                        <h1 style="font-style :italic;">
                            Your Deadline
                        </h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 align-text-center text-center">
                        <div class="container container-bodycolor p-3 rounded-lg mb-2 mt-3">
                            <div class="container text-left mb-3">
                                <h4>Your Task :</h4>
                            </div>
                            <div class="container bg-white rounded-lg py-2 px-3 text-justify">
                                <div class="row ml-2" style="height: 400px; max-height: 400px;">
                                    <div class="col mt-4 ml-3 px-0" style="height: 350px; overflow-y: scroll;" id="undone_task">
                                        {% for i in list_dl %}
                                            {% if not i.selesai %}
                                                    <p>
                                                        {{ i.nama_deadline }}
                                                        <a href="{% url 'deadline:done' pk=i.pk %}"><button class="btn btn-icon btn-danger" style="position: absolute; right:30px;"><i class="fa fa-trash"></i>Done</button></a>
                                                    </p>
                                                <br>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="row ml-2 mb-2">
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <!-- <form method="POST" id="submit_deadline"> -->
                                        {% csrf_token %}
                                        {{ form }}
                                        <!-- </form> -->
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <button id="submit_button" class="btn btn-icon btn-danger" style="margin-top: 30px;"><i class="fa fa-trash"></i>Submit</button>
                                    </div>
                                </div>
                                <div class="row">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 text-center">
                        <div class="container container-bodycolor p-3 rounded-lg mb-2 mt-3" style="height:570px">
                            <div class="container text-left mb-3">
                                <h4>Done Task :</h4>
                            </div>
                            <div class="container bg-white rounded-lg py-2 px-3 text-justify" style="height: 495px;">
                                <div class="row ml-2" style="max-height: 400px;">
                                    <div class="col mt-4 ml-3" style="height: 350px; overflow-y: scroll;" >
                                        {% for j in list_dl %}
                                            {% if j.selesai %}
                                                    <p>
                                                        {{ j.nama_deadline }}
                                                        <a href="{% url 'deadline:erase' pk=j.pk %}"><button class="btn btn-icon btn-danger" style="position: absolute; right:120px; margin-right: 5px;"><i class="fa fa-trash"></i>Delete</button></a>
                                                        <a href="{% url 'deadline:undone' pk=j.pk %}"><button class="btn btn-icon btn-danger" style="position: absolute; right:30px;"><i class="fa fa-trash"></i>Undone</button></a>
                                                    </p>
                                                <br>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12 text-center">
                        <div class="container container-bodycolor p-3 rounded-lg mb-2 mt-3">
                            <div class="container text-left mb-3">
                                <h4>Summary :</h4>
                            </div>
                            <div class="container bg-white rounded-lg py-2 px-3 text-justify">
                                <p id = "undone_task_summary">
                                    Your Task : {{belum}}
                                </p>
                                <p>
                                    Done Task : {{sudah}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock content %}

        {% block script %}
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="{% static 'deadline/js/scrollreveal.js' %}" type="text/javascript"></script>
        <script>
            window.sr = ScrollReveal();
            sr.reveal('.container-bodycolor', { duration: 1000 });
            $('#submit_button').click( function(event){
                // console.log('masuk');
                event.preventDefault();
                tambah_deadline();
            })
            function tambah_deadline(){
                $.ajax({
                    url: 'http://proj-nara.herokuapp.com/deadline/add_dl_service/',
                    // url: 'http://localhost:8000/deadline/add_dl_service/',
                    type: 'POST',
                    data : {
                        "daftar_deadline" : $('#id_daftar_deadline').val(),
                        "csrfmiddlewaretoken" : $("input[name = csrfmiddlewaretoken]").val(),
                    },
                    success: function (result) {
                        // result.s
                        // console.log(result)
                        result = JSON.parse(result.results);
                        $("#undone_task").html("");
                        var belum = 0;
                        for ( var i = 0 ; i < result.length ; i++)
                        {
                            var x = ``
                            x += `<p>
                                        `+ result[i].fields.nama_deadline + `
                                        <a href="/deadline/` + result[i].pk +`"><button class="btn btn-icon btn-danger" style="position: absolute; right:30px;"><i class="fa fa-trash"></i>Done</button></a>
                                    </p>
                                <br>`
                            $("#undone_task").append(x)
                            
                            if(result[i].fields.selesai == true){
                                belum+=1;
                            }
                        }
                        var y = ``
                        var z =  result.length - belum 
                        y += `<p>
                                Your Task : ` + z +`
                            </p>`
                            $("#undone_task_summary").html("")
                        $("#undone_task_summary").append(y)
                        $('#id_daftar_deadline').val("")
                    }
                });
            }
            
        </script>
        {% endblock %}
    </body>