jadwal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import CalendarView, event

app_name = "jadwal"

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/$', event, name='event_new'),
    path('event/edit/<int:event_id>', event, name='event_edit'),
]

nara_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('deadline/', include('deadline.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('profil/', include('profil.urls')),
    path('nilai/', include('nilai.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nilai/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.masuk_data, name='idx'),
	path('hitung/', views.hitung_ip, name='hitung'),
	path('hapus/', views.reset, name='hapus'),
	path('getData/', views.getJSON, name='ambil'),
]

jadwal/models.py
from django.db import models

from django.urls import reverse
# Create your models here.


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('jadwal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

jadwal/forms.py
from django.forms import ModelForm, DateInput
from .models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

jadwal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from jadwal.models import *
from .utils import Calendar
from .forms import EventForm


class CalendarView(generic.ListView):
    model = Event
    template_name = 'jadwal/jadwal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        jadwal = Calendar(d.year, d.month)
        html_jadwal = jadwal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_jadwal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('jadwal:calendar'))
    return render(request, 'jadwal/event.html', {'form': form})

jadwal/templates/jadwal/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'jadwal/css/style.css' %}">
{% endblock %}
  
  {% block content %}
  <div class="clearfix">
    <a class="btn btn-info left" href="{% url 'jadwal:calendar' %}"> Calendar </a>
  </div>
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <table class="form form-table" id="page">
      {{ form }}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
    </table>
  </form>
  {% endblock %}

  {% block script %}
  {% endblock %}

jadwal/templates/jadwal/event.html
{% extends 'jadwal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'jadwal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table" id="page">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

jadwal/templates/jadwal/jadwal.html
{% extends 'jadwal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="container-fluid">

  <div class="clearfix">

      <button onclick="getElementById('tang').innerHTML=Date()">What is the time?</button>
      <p id="tanggal"></p>
        
    <a class="btn btn-info left"  href="{% url 'jadwal:calendar' %}?{{ prev_month }}"> Previous Month </a>
    <a class="btn btn-info right" href="{% url 'jadwal:calendar' %}?{{ next_month }}"> Next Month </a>
    <a class="btn btn-info right" href="{% url 'jadwal:event_new' %}"> New Event </a>
  </div>
  <div class="container" style="margin-top: 40px;">
    <h1>
      <b>
        <i>
          Schedule Planner
        </i>
      </b>
    </h1>
  </div>
  <div class="container py-4" style="background-color: aquamarine;border-radius: 2%;">
    <div class="container">
      <div class="row" >
        <div class="container my-1 mx-3" style="width: 100%;">
          <div class="col-sm bg-white my-3 px-0" style="width: 100%;">
            {{ calendar }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="event" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="event">Aktifitas Baru</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
{% endblock %}
{%block script%}
{% endblock%}